/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class Library {
    //Rolling Dice
    public static void roll(int n) {
        int arr[] = new int[n];

        for (int i = 0; i < n; i++) {
            arr[i] = (int) (Math.random() * ((6 - 1) + 1)) + 1;
        }

        System.out.println(Arrays.toString(arr));
    }

    //Contains Duplicates
    public static boolean containsDuplicates(int[] arr) {
        // intilize empty hashset
        Set<Integer> set = new HashSet<Integer>();

        // fill the hashset with array content
        for (int i : arr) {
            set.add(i);
        }

        // if the hashset size equal to array length so there is no duplicates (cuz hashset remove duplicates)
        if (set.size() != arr.length) {
            return true;
        } else {
            return false;
        }
    }

    //Calculating Averages
    public static double calculateAvg(int[] arr) {
        int sum = 0;
        for (int i : arr) {
            sum += i;
        }
        return sum / (double) arr.length;
    }

    //Arrays of Arrays
    public static int[] arrayOfArrays(int[][] arr2d) {
        double avg = 0;
        int arrOut[] = new int[arr2d[0].length];

        for (int[] arr1d : arr2d) {
            if (calculateAvg(arr1d) < avg ) {
                arrOut = arr1d;
            }
            avg = calculateAvg(arr1d);
        }

        return arrOut;
    }

    public static void main(String[] args) {
        System.out.println("--------- task 1 ----------");
        //Rolling Dice
        roll(6);

        System.out.println("--------- task 2 ----------");
        //Contains Duplicates
        int arr[] = {1, 2, 3, 2};
        System.out.println(containsDuplicates(arr));

        System.out.println("--------- task 3 ----------");
        //Calculating Averages
        int arr2[] = {1, 2, 3};
        System.out.println(calculateAvg(arr2));

        System.out.println("--------- task 4 ----------");
        //Arrays of Arrays
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println(Arrays.toString(arrayOfArrays(weeklyMonthTemperatures)));
    }
}
